#!/usr/bin/env bash
# Universal Global AI Configuration Synchronization Engine (Bash)
set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[AI-SYNC]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[AI-SYNC]${NC} $1"
}

# Resolve paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GLOBAL_AI_DIR="$HOME/.ai"

ensure_symlink() {
    local src="$1"
    local dest="$2"

    if [[ -L "$dest" && "$(readlink "$dest")" == "$src" ]]; then
        log_info "Symlink $dest -> $src is up to date."
        return
    fi

    if [[ -e "$dest" || -L "$dest" ]]; then
        if [[ -d "$dest" && ! -L "$dest" ]]; then
            log_info "Backing up existing directory $dest to ${dest}.bak"
            mv "$dest" "${dest}.bak"
        else
            log_info "Removing existing target/link $dest"
            rm -rf "$dest"
        fi
    fi

    mkdir -p "$(dirname "$dest")"
    ln -s "$src" "$dest"
    log_success "Created symlink: $dest -> $src"
}

# 1. Symlink ~/.ai -> repo dotfiles/ai
if [[ "$SCRIPT_DIR" != "$GLOBAL_AI_DIR" ]]; then
    ensure_symlink "$SCRIPT_DIR" "$GLOBAL_AI_DIR"
fi

# 2. Sync Skills
SKILLS_SRC="$GLOBAL_AI_DIR/skills"
if [[ -d "$SKILLS_SRC" ]]; then
    ensure_symlink "$SKILLS_SRC" "$HOME/.claude/skills"
    ensure_symlink "$SKILLS_SRC" "$HOME/.gemini/config/skills"
fi

# 3. Sync Rules
RULES_DIR="$GLOBAL_AI_DIR/rules"
if [[ -d "$RULES_DIR" ]]; then
    COMBINED_RULES="<!-- AUTO-GENERATED BY ~/.ai/sync.sh - DO NOT EDIT DIRECTLY -->\n\n"
    for rfile in "$RULES_DIR"/*.md; do
        [[ -f "$rfile" ]] || continue
        fname="$(basename "$rfile")"
        rcontent="$(cat "$rfile")"
        COMBINED_RULES="${COMBINED_RULES}<!-- Rule: ${fname} -->\n${rcontent}\n\n"
    done

    RULE_TARGETS=(
        "$HOME/.claude/CLAUDE.md"
        "$HOME/.gemini/config/rules/global_rules.md"
        "$HOME/.cursorrules"
        "$HOME/.windsurfrules"
    )

    for target in "${RULE_TARGETS[@]}"; do
        mkdir -p "$(dirname "$target")"
        echo -e "$COMBINED_RULES" > "$target"
        log_success "Updated rule file: $target"
    done
fi

# 4. Sync Claude Code permissions & hooks
PERM_FILE="$GLOBAL_AI_DIR/permissions.json"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
HOOK_SCRIPT="$GLOBAL_AI_DIR/hooks/tab-blink.sh"

mkdir -p "$HOME/.claude"

if [[ -f "$CLAUDE_SETTINGS" ]]; then
    EXISTING_SETTINGS="$(cat "$CLAUDE_SETTINGS")"
else
    EXISTING_SETTINGS="{}"
fi

if [[ -f "$PERM_FILE" && -x "$(command -v jq)" ]]; then
    # Parse permissions and replace $HOME with actual home path
    RESOLVED_PERMS="$(jq --arg home "$HOME" '
        .permissions.allow |= map(gsub("\\$HOME"; $home))
    ' "$PERM_FILE")"

    # Merge permissions and hooks into existing Claude settings
    UPDATED_SETTINGS="$(echo "$EXISTING_SETTINGS" | jq \
        --argjson perms "$RESOLVED_PERMS" \
        --arg hook "$HOOK_SCRIPT" '
        .permissions = $perms.permissions |
        .hooks = {
            "Notification": [{"hooks": [{"type": "command", "command": ("\"" + $hook + "\" set"), "async": true}]}],
            "Stop": [{"hooks": [{"type": "command", "command": ("\"" + $hook + "\" set"), "async": true}]}],
            "UserPromptSubmit": [{"hooks": [{"type": "command", "command": ("\"" + $hook + "\" clear"), "async": true}]}]
        }
    ')"

    echo "$UPDATED_SETTINGS" > "$CLAUDE_SETTINGS"
    log_success "Updated Claude Code settings & permissions: $CLAUDE_SETTINGS"
fi

# 5. Sync Antigravity hooks
GEMINI_HOOKS="$HOME/.gemini/config/hooks.json"
mkdir -p "$HOME/.gemini/config"

if [[ -x "$(command -v jq)" ]]; then
    jq -n --arg hook "$HOOK_SCRIPT" '{
        "Notification": [{"type": "command", "command": ("\"" + $hook + "\" set"), "async": true}],
        "Stop": [{"type": "command", "command": ("\"" + $hook + "\" set"), "async": true}],
        "UserPromptSubmit": [{"type": "command", "command": ("\"" + $hook + "\" clear"), "async": true}]
    }' > "$GEMINI_HOOKS"
    log_success "Updated Antigravity hooks config: $GEMINI_HOOKS"
fi

log_success "Global AI configuration sync completed successfully!"
